### ISSUE TITLE
Miniplex 2.0 Release Checklist

### ISSUE THREAD

**Issue by hmans** [hmans/miniplex#287]
Time to get 2.0 out of the door. Here's a list of things I want or need to do — not all of them need to be done before the actual release:

- [x] Upgrade to Typescript 5.x
- [x] Upgrade most/all dependencies
- [x] Change packages so `miniplex` is just the core and `miniplex-react` is the React bindings
- [x] Documentation
  - [x] Check and update core package documentation
  - [x] Check and update React package documentation
- [x] Write release notes (probably just copy & amend the 2.0 Beta release notes)
- [x] Fix the Vercel deployment issues for the demo apps
- [x] Figure out why the React demo breaks with the newest Three.js/R3F bits. I won't have time to look into this (or build a new demo), so maybe someone else can investigate?
- [ ] Blog about the release, and the future of the package (and my web gamedev work in general)

Not 100% critical for a 2.0 release, but should do these too:

- [x] Resolve the dependency to @hmans/event 0.2.0. There's Eventery now, maybe use that?
- [ ] Publish `@miniplex/bucket` as `bucketeer`

**Comment by hmans** [comment]
Closing, as 2.0 has now been released.
