### ISSUE TITLE
0.8.0 Release Checklist

### ISSUE THREAD

**Issue by hmans** [hmans/miniplex#6]
I'm preparing a 0.8.0 release for Miniplex. The library is now sufficiently stable that I want to start documenting and promoting it without putting an "experimental" disclaimer on everything, so this is going to be a significant release! This issue here serves as a checklist for things that need to happen before the release can be happen.

If you've used Miniplex in your own projects and have opinions on it (specifically usage ergonomics, which I want to be as great as we can make them), please chime in!

### Checklist:

- [x] #7 
- [x] Write additional tests, especially for the new React bits mentioned above
- [x] Extract the React bits into a separate package (eg. `miniplex-react`)

### Documentation Checklist:

- [x] Update README with up to date usage information
- [x] Document the automatically generated `id` component
- [x] Document all the new React glue (specifically `<Entities>` and `<Collection>`)

### Misc/Followup:

- [ ] Update the WIP benchmark submissions (and finally submit them!)
- [ ] Update the Boids demo to use the new version
- [ ] Maybe provide a demo that is even more basic than the Boids demo

**Comment by hmans** [comment]
0.8.0 is out. There may be additional changes to `miniplex-react`, which is versioned separately from the main package.
